# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBlGcrvtNSO2cEq_TFZpimcV_ALMVork
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# ===============================
# Load model and training columns
# ===============================
with open("linear_regression_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("preprocessed_energy_data.pkl", "rb") as f:
    train_data = pickle.load(f)

# Extract feature columns used during training
feature_columns = train_data.drop("Energy Consumption", axis=1).columns

# ===============================
# Streamlit UI
# ===============================
st.set_page_config(page_title="Energy Consumption Prediction", layout="centered")

st.title("⚡ Energy Consumption Prediction App")
st.markdown("Predict energy consumption based on building and environmental factors.")

# ===============================
# User Inputs
# ===============================
temperature = st.number_input("🌡 Temperature (°C)", min_value=0.0, max_value=60.0, value=25.0)
no_of_occupant = st.number_input("Number of Occupant", min_value=0.0, max_value=100.0, value=60.0)
appliances = st.number_input("Appliances used", min_value=0.0, max_value=100.0, value=60.0)
square_footage = st.number_input("🏢 Square Footage", min_value=100, max_value=1000000, value=1000)

building_type = st.selectbox(
    "🏠 Building Type",
    ["Residential", "Commercial", "Industrial"]
)

day_of_week = st.selectbox(
    "📅 Day of Week",
    ["Weekday", "Weekend"]
)

# ===============================
# Prepare input data
# ===============================
input_df = pd.DataFrame({
    "Temperature": [temperature],
    "Number of Occupant": [no_of_occupant],
    "Appliances used": [appliances],
    "Square Footage": [square_footage],
    "Building Type": [building_type],
    "Day of Week": [day_of_week]
})

# One-hot encoding (same as training)
input_df = pd.get_dummies(
    input_df,
    columns=["Building Type", "Day of Week"],
    drop_first=True
)

# 🔥 VERY IMPORTANT FIX
input_df = input_df.reindex(columns=feature_columns, fill_value=0)

# ===============================
# Prediction
# ===============================
if st.button("🔮 Predict Energy Consumption"):
    prediction = model.predict(input_df)
    st.success(f"⚡ Estimated Energy Consumption: **{prediction[0]:.2f} kWh**")